# Generated by Django 2.2.15 on 2020-08-11 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ts_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.BooleanField(default=False)),
                ('email', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=120, null=True)),
                ('text', models.TextField(default='', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
