# Generated by Django 2.2.12 on 2020-09-03 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200903_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fire_token',
            new_name='package',
        ),
        migrations.RemoveField(
            model_name='user',
            name='membership_end_date',
        ),
    ]
