# Generated by Django 2.2.12 on 2020-09-13 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200913_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='a',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ae',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='amountLeft',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='anyOtherExpenseThisMonth',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='b',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='be',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='budget',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='budgetLeft',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='expense',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fakeIncomeDate',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstWeekendBudget',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='goalDate',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='goalStart',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='incomeLeft',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='member',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='monthlyIncome',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='need',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='projectedExpense',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='realExpense',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondWeekendBudget',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='startFrom',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='surplus',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='target',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='todaysBudget',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='todaysExpense',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='totalBasicexpense',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='totalBudget',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weekDaysBudget',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weekendOne',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weekendTwo',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
